
// Get Website
export const FETCH_ORDER_BEGIN = 'FETCH_ORDER_BEGIN '
export const FETCH_ORDER_END = 'FETCH_ORDER_END'
export const RECIEVE_ORDER = 'RECIEVE_ORDER'

export const FETCH_DRAFT_BEGIN = 'FETCH_DRAFT_BEGIN'
export const FETCH_DRAFT_END = 'FETCH_DRAFT_END'
export const RECIEVE_DRAFT = 'RECIEVE_DRAFT'


export const RECIEVE_CACHE_ORDER = 'RECIEVE_CACHE_ORDER'
export const CACHE_ORDER_BEGIN = 'CACHE_ORDER_BEGIN '


//CAMPAIGN
export const RECEIVE_CAMPAIGN_DETAIL = 'RECEIVE_CAMPAIGN_DETAIL'
export const RECEIVE_CAMPAIGN_NOTIFICATION = 'RECEIVE_CAMPAIGN_NOTIFICATION'
