
// Get Website
export const FETCH_ORDER_BEGIN = 'FETCH_ORDER_BEGIN '
export const FETCH_ORDER_END = 'FETCH_ORDER_END'
export const RECIEVE_ORDER = 'RECIEVE_ORDER'


//CAMPAIGN
export const RECEIVE_CAMPAIGN_DETAIL = 'RECEIVE_CAMPAIGN_DETAIL'
export const RECEIVE_CAMPAIGN_NOTIFICATION = 'RECEIVE_CAMPAIGN_NOTIFICATION'
