export const Item = {
  product: '',
  material: '',
  backing: '',
  pe: '',
  border: '',
  cut: '',
  packaging: '',
  setQty: [],
  optionalItem: '',
  markup: '0',
  discountApply: false,
  wLeft: '1',
  wRight: '0',
  wCenter: '0',
  hLeft: '1',
  hCenter: '0',
  hRight: '0',
  size: 1,
  data: [],
  colors: [],
  pmsColors: []
};
